### ISSUE TITLE
Connecting between app and CloudLog

### ISSUE THREAD

**Issue by Michael-AUG** [mbridak/CloudLogPyCAT#3]
Hi. Thanks for making your app which is the only one I've been able to get to work on my RaspPi.
However, CloudLog is not registering the radio. I've checked (and checked and double checked) that the API and CloudLog URL are correct, but it still isn't showing.
Is there any advice you could offer? Many thanks.
73 de Michael GM5AUG

**Comment by mbridak** [comment]
Hi, the "Radio Name" in the CloudLogPyCAT settings dialog is sent to Cloudlog and you should be able to select the radio name that was sent in the Cloudlog QSO Live or QSO Contest window. Once it's selected it should start showing to correct vfo/mode information.

If you don't see the radio name from settings as a selectable option, spin the vfo knob a little bit. once the program sees a frequency change it will resend it to cloudlog. Reload the cloudlog qso window and recheck for your radio name in the drop down.

![Screenshot from 2023-03-25 15-15-51](https://user-images.githubusercontent.com/49108421/227745420-759610da-65d0-48a3-ad66-a67d1291b41c.png)

![Screenshot from 2023-03-25 15-16-34](https://user-images.githubusercontent.com/49108421/227745377-45b27cf9-f58b-45c3-8c42-cb89ad56b228.png)

![Screenshot from 2023-03-25 15-17-21](https://user-images.githubusercontent.com/49108421/227745468-31b6ed88-9836-4ba4-bf05-b316f1dcfda2.png)

**Comment by Michael-AUG** [comment]
Thanks so much. I should have guessed it was as simple as turning the VFO knob a little to force an updated frequency to the server! Excellent app - thank you very much. 73 es GL de Michael GM5AUG
