### ISSUE TITLE
Feature request: send rig power to Cloudlog

### ISSUE THREAD

**Issue by mattbk** [mbridak/CloudLogPyCAT#4]
The Cloudlog API now allows rig power to be sent: https://github.com/magicbug/Cloudlog/pull/1451. It would be nice to add to CloudLogPyCAT. Thanks for considering.

**Comment by mbridak** [comment]
I'll consider it.
Thanks.

**Comment by aviatorhh** [comment]
See latest pull request of mine.

**Comment by mbridak** [comment]
It's merged, Thanks for the PR!
